name: Test

on:
  push:
  pull_request:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - run: corepack enable
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: npm
      - run: |
          npm ci
          echo "$(pwd)/node_modules/.bin" >> "$GITHUB_PATH"
      - run: npx prettier --check .
      - run: |
          npx tree-sitter generate
          git diff --exit-code
      - uses: tree-sitter/parser-test-action@aba4a3de737f86f8ce83be38166a1ab521d4c960 # v2
        with:
          generate: false
      - uses: JohnnyMorganz/stylua-action@76fd70c03e6340ceaf673366712db9b20560b402 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.0.2
          args: --check .
