name: Test

on:
  push:
  pull_request:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: |
          npm ci
          echo "$(pwd)/node_modules/.bin" >> "$GITHUB_PATH"
      - run: npx prettier --check .
      - run: |
          npx tree-sitter generate
          git diff --exit-code
      - uses: tree-sitter/parser-test-action@v2
        with:
          generate: false
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.0.2
          args: --check .
