name: Test

on:
  push:
  pull_request:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
      - run: |
          pnpm install --frozen-lockfile
          echo "$(pwd)/node_modules/.bin" >> $GITHUB_PATH
      - run: pnpm exec prettier --check .
      - uses: tree-sitter/parser-test-action@v2
        with:
          generate: true
